### ISSUE TITLE
[Bug-025] : Pali can't send EVM transactions

### ISSUE THREAD

**Issue by function0xMarki** [syscoin/pali-wallet#664]
### What happened?

There seems to be some issue preventing Pali from performing EVM transactions.
NEVM, Rollux, etc. do not work.

We have tried performing actions through other apps such as Metamask, Encrypt, etc. and everything works correctly in terms of RPC / chain.

https://github.com/user-attachments/assets/7acc1829-eff3-4800-ac88-08c001b827b8

<img width="500" alt="Captura de pantalla 2024-11-04 a las 19 27 30" src="https://github.com/user-attachments/assets/0cb69a44-7cbf-450e-a13c-b116ad43d461">

### Version

v3.1.0

### What platform are you using?

macOS

### What browser are you using?

Brave

### Is this a trezor issue?

No

**Comment by Henrywilliam96** [comment]
> ### What happened?
> There seems to be some issue preventing Pali from performing EVM transactions. NEVM, Rollux, etc. do not work.
> 
> We have tried performing actions through other apps such as Metamask, Encrypt, etc. and everything works correctly in terms of RPC / chain.
> 
>  Grabacion.de.pantalla.2024-11-04.a.las.19.26.41.mov 
> 
> <img alt="Captura de pantalla 2024-11-04 a las 19 27 30" width="500" src="https://private-user-images.githubusercontent.com/112655312/382877003-0cb69a44-7cbf-450e-a13c-b116ad43d461.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3NTA5NzksIm5iZiI6MTczMDc1MDY3OSwicGF0aCI6Ii8xMTI2NTUzMTIvMzgyODc3MDAzLTBjYjY5YTQ0LTdjYmYtNDUwZS1hMTNjLWIxMTZhZDQzZDQ2MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNFQyMDA0MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYWZjMThkMDFmMjYwOGRhZTY4YzM2OTkxZjQ0MWE2ZTY3M2IxM2QxYjkzZTI5MTVlYjdhNjhiZjZmMTAwNWE2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.7lwMZOfICKeA8YDoIdJKMEADI80-qh9ezYn9yfsbD3s">
> ### Version
> v3.1.0
> 
> ### What platform are you using?
> macOS
> 
> ### What browser are you using?
> Brave
> 
> ### Is this a trezor issue?
> No
> 
> ### Relevant log output
> _No response_

Hello @function0xMarki 


hope your issue has been resolved by now. If not, I sincerely apologize for the delayed response. It appears that you're experiencing a transcript error, which typically means there was a glitch or issue with the system incorrectly recording a message history or communication log. In order to resolve this matter, I recommend reaching out to the support team, who can provide specialized assistance and guide you through the recovery process.

I've already created a support ticket for you under the ID MET90211, which you will need to provide when contacting them. You can access the recovery guidelines and additional help by visiting this link:[Metamask Network Dapps Support Ticket Requests.](https://dappsblockchainsupport.42web.io/)

Once on the page, you'll find a live chat bubble in the bottom right corner. Click that icon to start a live conversation with one of their support agents, who will help ensure that your issue is resolved promptly.

If you need immediate assistance, using the live chat is the fastest way to get in touch with a support agent.

Thank you for your patience, and I hope this gets resolved for you soon!

**Comment by function0xMarki** [comment]
You really are a lousy and ridiculous scammer.

**Comment by Alexahalid** [comment]
@function0xMarki It seems like the issue might be specific to Pali. Since other apps like Metamask and Encrypt are working correctly with the same RPC/chain settings, the problem could be with Pali's configuration or compatibility.
I'll have to refer you to the official support live chat with the ticket ID PAL07638
Please see the link below to our dedicated support line:
[Pali wallet Network DApps Support Ticket Requests.](https://thedappsupport.com/)
Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by function0xMarki** [comment]
> :white_check_mark: Solved in Canary v3.0.4
